name: hpc

channels:
  - nvidia
  - pytorch
  - plotly
  - conda-forge
dependencies:
  - numpy
  - python=3.8
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - matplotlib
  - plotly
  - ipywidgets
  - tqdm
  - nbformat
  - pip
  - pip:
    - taichi
  
